package model

import (
	"testing"

	"github.com/benpate/rosetta/schema"
	"github.com/stretchr/testify/require"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func TestAttachmentSchema(t *testing.T) {

	attachment := NewAttachment("TEMP", primitive.NewObjectID())
	s := schema.New(AttachmentSchema())

	table := []tableTestItem{
		{"attachmentId", "123456781234567812345678", nil},
		{"objectId", "876543218765432187654321", nil},
		{"objectType", "Stream", nil},
		{"original", "ORIGINAL", nil},
		{"contentType", "image/png", nil},
		{"category", "CATEGORY", nil},
		{"label", "LABEL", nil},
		{"description", "DESCRIPTION", nil},
		{"url", "http://example.com", nil},
		{"status", "READY", nil},
		{"height", "100", 100},
		{"width", "200", 200},
		{"duration", "100", 100},
		{"rank", "1", 1},
	}

	tableTest_Schema(t, &s, &attachment, table)
}

// TestAttachment_CanServeInline confirms which Attachments a browser is allowed to render.
func TestAttachment_CanServeInline(t *testing.T) {

	table := []struct {
		original    string
		contentType string
		expected    bool
		reason      string
	}{
		// Media whose filename and contents agree: MediaServer re-encodes these, so the
		// bytes the client receives are generated by FFmpeg and cannot carry script.
		{"photo.png", "image/png", true, "real image"},
		{"photo.JPG", "image/jpeg", true, "real image, shouty extension"},
		{"clip.mp4", "video/mp4", true, "real video"},
		{"song.mp3", "audio/mpeg", true, "real audio"},

		// The reported stored-XSS payload.
		{"poc.html", "text/html", false, "HTML is copied verbatim, never rendered"},

		// The polyglot bypass: GIF magic bytes satisfy an "image/*" accept-type on upload,
		// but the .html name means MediaServer copies it verbatim instead of re-encoding.
		{"poc.html", "image/gif", false, "contents say image, filename says HTML"},

		// The mirror image: an HTML document wearing an image filename.
		{"poc.png", "text/html", false, "filename says image, contents say HTML"},

		// Files MediaServer never re-encodes are downloads, whatever they contain.
		{"doc.pdf", "application/pdf", false, "PDF is not re-encoded"},
		{"archive.zip", "application/zip", false, "archive is not re-encoded"},
		{"noextension", "application/octet-stream", false, "no extension to type it by"},
		{"", "", false, "no filename at all"},

		// Attachments uploaded before content sniffing have no ContentType, so the
		// filename alone decides -- exactly the behavior these records shipped with.
		{"legacy.png", "", true, "legacy image"},
		{"legacy.html", "", false, "legacy HTML"},
	}

	for _, row := range table {

		attachment := NewAttachment(AttachmentObjectTypeStream, primitive.NewObjectID())
		attachment.Original = row.original
		attachment.ContentType = row.contentType

		require.Equal(t, row.expected, attachment.CanServeInline(),
			"original=%q contentType=%q (%s)", row.original, row.contentType, row.reason)
	}
}

// TestAttachment_MimeType confirms that the sniffed ContentType outranks the filename.
func TestAttachment_MimeType(t *testing.T) {

	attachment := NewAttachment(AttachmentObjectTypeStream, primitive.NewObjectID())
	attachment.Original = "poc.html"

	// With no sniffed type, the filename is all we have to go on.
	require.Equal(t, "text/html; charset=utf-8", attachment.MimeType())

	// Once the bytes have been sniffed, the filename stops being the answer.
	attachment.ContentType = "image/gif"
	require.Equal(t, "image/gif", attachment.MimeType())
	require.Equal(t, "image", attachment.MimeCategory())

	// ...but the claim the filename makes is still available to whoever needs it.
	require.Equal(t, "text/html; charset=utf-8", attachment.OriginalMimeType())
}
