package model

// NamespaceEmissary prefixes JSON-LD properties that are generated by this server itself.
// Inbound values in this namespace are forgeries, and are stripped at every trust boundary:
// the assanitizer client in the ActivityStream stack, and the inbox receive funnel.
const NamespaceEmissary = "emissary:"

// PropertyEmissaryLabels is the JSON-LD property that carries a document's rule labels
// (serialized as [{value, href, isHidden}]) when served to this User's own clients.
const PropertyEmissaryLabels = "emissary:labels"
