package model

import (
	"github.com/benpate/data/journal"
	"github.com/benpate/form"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Product links to a product plan that a User has configured on their
// own account with a PaymentService.
type Product struct {
	ProductID           primitive.ObjectID `bson:"_id"`                 // Unique ID for the product
	UserID              primitive.ObjectID `bson:"userId"`              // Unique ID of the user who owns the product
	MerchantAccountID   primitive.ObjectID `bson:"merchantAccountId"`   // The MerchantAccount used to pay for this product
	MerchantAccountType string             `bson:"merchantAccountType"` // The type of MerchantAccount used to pay for this product (STRIPE, PAYPAL)
	RemoteID            string             `bson:"remoteId"`            // Unique ID of the product plan (generated by the payment processor)
	Name                string             `bson:"name"`                // Human-friendly name of the product
	Description         string             `bson:"description"`         // Human-friendly description of the product
	Price               string             `bson:"paymentAmount"`       // Human-friendly descrption of the Price (e.g. $5.00/month)
	RecurringType       string             `bson:"recurringType"`       // Type of recurring payment (e.g., ONETIME, WEEKLY, MONTHLY, YEARLY)
	IsFeatured          bool               `bson:"isFeatured"`          // If true, then this product is featured on the User's profile page

	// Embed journal to track changes
	journal.Journal `bson:",inline"`
}

// NewProduct returns a fully initialized Product object
func NewProduct() Product {
	return Product{
		ProductID: primitive.NewObjectID(),
	}
}

// ID returns the unique ID of this Product
func (product Product) ID() string {
	return product.ProductID.Hex()
}

func (product Product) Fields() []string {
	return []string{
		"_id",
		"merchantAccountId",
		"merchantAccountType",
		"name",
		"description",
		"isFeatured",
	}
}

/******************************************
 * RoleStateEnumerator Interface
 ******************************************/

// State returns the current state of this object.
// For products, there is no state, so it returns ""
func (product Product) State() string {
	return ""
}

// Roles returns a list of all roles that match the provided authorization.
// Since Products records should only be accessible by the Product owner, this
// function only returns MagicRoleMyself if applicable.  Others (like Anonymous
// and Authenticated) should never be allowed on an Product record, so they
// are not returned.
func (product Product) Roles(authorization *Authorization) []string {

	// Products are private, so only 'myself' and 'owner' are allowed
	if authorization.UserID == product.UserID {
		return []string{MagicRoleMyself, MagicRoleOwner}
	}

	// Intentionally NOT allowing MagicRoleAnonymous, or MagicRoleAuthenticated
	return []string{MagicRoleOwner}
}

/******************************************
 * Other Methods
 ******************************************/

func (product Product) LookupCode() form.LookupCode {
	return form.LookupCode{
		Value:       product.ID(),
		Label:       product.Name,
		Description: product.Description,
	}
}
