package ascache

import "time"

// LoadConfig is a configuration object that used by the Load() method.
// It is generated by combining a default value with any functional
// options that are passed to the Load() method.
type LoadConfig struct {
	mode           string
	timeoutSeconds int
	minAge         time.Duration
}

// tryCache returns TRUE if the system should check the cache before loading an HTTP resource
func (config LoadConfig) tryCache() bool {
	return config.isReadAllowed() || config.hasMinAge()
}

// isReadAllowed returns TRUE when this config permits the normal (freshness-checked) cache read.
func (config LoadConfig) isReadAllowed() bool {
	return config.mode != CacheModeWriteOnly
}

// isWriteAllowed returns TRUE when this config permits writing the origin's response back to the cache.
func (config LoadConfig) isWriteAllowed() bool {
	return config.mode != CacheModeReadOnly
}

// hasMinAge returns TRUE when this config sets a cooldown before the origin may be contacted again.
func (config LoadConfig) hasMinAge() bool {
	return config.minAge > 0
}

// LoadOption is a functional option that can be passed to the Load() method.
type LoadOption func(*LoadConfig)

// NewLoadConfig creates a new LoadConfig object, and applies any functional options that are passed to it.
func NewLoadConfig(options ...any) LoadConfig {
	result := LoadConfig{
		mode:           CacheModeReadWrite,
		timeoutSeconds: 10,
	}

	result.With(options...)
	return result
}

// With applies functional options to the LoadConfig object
func (config *LoadConfig) With(options ...any) {
	for _, option := range options {
		if typed, ok := option.(LoadOption); ok {
			typed(config)
		}
	}
}

// WithTimeout is a functional option that sets the timeout (in seconds) for loading from the cache.
func WithTimeout(seconds int) LoadOption {
	return func(config *LoadConfig) {
		config.timeoutSeconds = seconds
	}
}

// WithReadWrite is a functional option that sets the cache mode to READWRITE.
func WithReadWrite() LoadOption {
	return func(config *LoadConfig) {
		config.mode = CacheModeReadWrite
	}
}

// WithReadOnly is a functional option that sets the cache mode to READONLY.
// By skipping WRITE steps, this mode only reads existing cache values and will not
// create or update any cache entries.
func WithReadOnly() LoadOption {
	return func(config *LoadConfig) {
		config.mode = CacheModeReadOnly
	}
}

// WithWriteOnly is a functional option that sets the cache mode to WRITEONLY.
// By skipping READ steps, this mode flushes any existing cache values and writes new values only.
func WithWriteOnly() LoadOption {
	return func(config *LoadConfig) {
		config.mode = CacheModeWriteOnly
	}
}

// WithMinAge is a functional option that contacts the origin only when the cached entry is older
// than minAge.  A fresher entry is returned as-is, even in WRITEONLY mode.
func WithMinAge(minAge time.Duration) LoadOption {

	// Refetching a document we pulled seconds ago cannot produce a different answer, so the only
	// thing it produces is an outbound request. That matters because the caller that forces a
	// reload here does so in response to a FAILED signature -- something an attacker can trigger at
	// will, naming any keyId host they like. The cooldown caps that at one fetch per minAge. (BUG-22)
	return func(config *LoadConfig) {
		config.minAge = minAge
	}
}
