package ascache

// LoadConfig is a configuration object that used by the Load() method.
// It is generated by combining a default value with any functional options that are passed to the Load() method.
type LoadConfig struct {
	mode           string
	timeoutSeconds int
}

func (config LoadConfig) isReadAllowed() bool {
	return config.mode != CacheModeWriteOnly
}

func (config LoadConfig) isWriteAllowed() bool {
	return config.mode != CacheModeReadOnly
}

// LoadOption is a functional option that can be passed to the Load() method.
type LoadOption func(*LoadConfig)

// NewLoadConfig creates a new LoadConfig object, and applies any functional options that are passed to it.
func NewLoadConfig(options ...any) LoadConfig {
	result := LoadConfig{
		mode:           CacheModeReadWrite,
		timeoutSeconds: 10,
	}

	result.With(options...)
	return result
}

// With applies functional options to the LoadConfig object
func (config *LoadConfig) With(options ...any) {
	for _, option := range options {
		if typed, ok := option.(LoadOption); ok {
			typed(config)
		}
	}
}

// WithTimeout is a functional option that sets the timeout (in seconds) for loading from the cache.
func WithTimeout(seconds int) LoadOption {
	return func(config *LoadConfig) {
		config.timeoutSeconds = seconds
	}
}

// WithReadWrite is a functional option that sets the cache mode to READWRITE.
func WithReadWrite() LoadOption {
	return func(config *LoadConfig) {
		config.mode = CacheModeReadWrite
	}
}

// WithReadOnly is a functional option that sets the cache mode to READONLY.
// By skipping WRITE steps, this mode only reads existing cache values and will not
// create or update any cache entries.
func WithReadOnly() LoadOption {
	return func(config *LoadConfig) {
		config.mode = CacheModeReadOnly
	}
}

// WithWriteOnly is a functional option that sets the cache mode to WRITEONLY.
// By skipping READ steps, this mode flushes any existing cache values and writes new values only.
func WithWriteOnly() LoadOption {
	return func(config *LoadConfig) {
		config.mode = CacheModeWriteOnly
	}
}
