version: '3.8'
services:
  emissary:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EMISSARY_CONFIG=file:///data/config/config.json
    command: ["./wait-entrypoint.sh"]
    depends_on:
      - mongodb
      - smtp
    volumes:
      - configdata:/data/config
  setup:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - EMISSARY_CONFIG=file:///data/config/config.json
    command: ["./emissary", "--port", "8888", "--setup"]
    depends_on:
      - mongodb
      - smtp
    volumes:
      - configdata:/data/config
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  smtp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-smtpLogger
    ports:
        - "8025:8025"
volumes:
  mongodata:
  configdata:
