# This docker-compose file starts up a Emissary server where you
# can "kick the tires" and see how it works. You should probably 
# not use this in production.
# 
# It defaults to serving one domain "localhost" on port 8080.
name: emissary_demo

services:

  # This is the Emissary server that runs a single "localhost" domain on port 8080.
  emissary:
    container_name: demo_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile-demo
    ports:
      - "8080:8080"
    environment:
      - EMISSARY_CONFIG=file:///data/config/demo.json
    depends_on:
      - mongodb
    volumes:
      - configdata:/data/config
      - uploadfiles:/data/uploads

  # The setup tool creates/modifies the server configuration,
  # although you probably won't have to use it much for this demo.
  setup:
    container_name: demo_setup
    build:
      context: .
      dockerfile: ./docker/Dockerfile-demo
    ports:
      - "8888:8888"
    environment:
      - EMISSARY_CONFIG=file:///data/config/demo.json
    command: ["--setup", "--port", "8888"]
    depends_on:
      - mongodb
    volumes:
      - configdata:/data/config

  # This mongo database stores data for the Emissary site.
  mongodb:
    container_name: demo_database
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  configdata:
  mongodata:
  uploadfiles:
