// Package assanitizer enforces reserved property namespaces on ActivityStreams documents. Values
// in a reserved namespace (like "emissary:") are generated by this server and carry trust --
// moderation marks, rule labels -- so any that ARRIVE from the outside are forgeries. The Client
// is a hannibal streams.Client middleware that sits at the trust boundary of the client stack,
// directly above the wire-facing lookup clients, so every layer above it (including the cache at
// rest) only ever sees server-generated values in those namespaces. The same Strip function is
// called directly by the inbox receive funnel, which parses POSTed activities that never pass
// through this stack.
package assanitizer

import (
	"github.com/benpate/hannibal/streams"
)

// Client is the streams.Client middleware. It strips reserved prefixes from every Load result and
// every Save input, and passes Delete through unchanged.
type Client struct {
	innerClient streams.Client
	prefixes    []string
}

// New returns a Client wrapping the innerClient, stripping properties in the reserved prefixes.
func New(innerClient streams.Client, prefixes ...string) *Client {

	result := &Client{
		innerClient: innerClient,
		prefixes:    prefixes,
	}

	result.innerClient.SetRootClient(result)
	return result
}

// SetRootClient forwards the top-level client pointer to the inner client.
func (client *Client) SetRootClient(rootClient streams.Client) {
	if client.innerClient != nil {
		client.innerClient.SetRootClient(rootClient)
	}
}

// Load fetches the document from the inner client, then strips reserved properties from it.
func (client *Client) Load(uri string, options ...any) (streams.Document, error) {

	document, err := client.innerClient.Load(uri, options...)

	if err != nil {
		return document, err
	}

	// Strip in place: Value() is a live reference to the document's containers.
	Strip(document.Value(), client.prefixes...)

	// Squeaky clean.
	return document, nil
}

// Save strips reserved properties from the document, then forwards it to the inner client, so
// nothing dirty passes through this client in either direction.
func (client *Client) Save(document streams.Document) error {
	Strip(document.Value(), client.prefixes...)
	return client.innerClient.Save(document)
}

// Delete forwards to the inner client.
func (client *Client) Delete(documentID string) error {
	return client.innerClient.Delete(documentID)
}
