spec:
  name: emissary
  services:
  - name: server
    git:
      branch: main
      repo_clone_url: https://github.com/EmissarySocial/emissary.git
    dockerfile_path: ".docker/prod-dockerfile"
    envs:
    - key: EMISSARY_CONFIG
      value: "mongodb://<mongodb-connection-string>"
      type: SECRET
  