package emojikey

type Emoji struct {
	Character   string
	Description string
}

// Emojis returns the canonical list of emoji characters used to generate emoji keys.
func Emojis() []Emoji {

	return []Emoji{
		{Character: "🐶", Description: "Dog"},
		{Character: "🐱", Description: "Cat"},
		{Character: "🦁", Description: "Lion"},
		{Character: "🐎", Description: "Horse"},
		{Character: "🦄", Description: "Unicorn"},
		{Character: "🐷", Description: "Pig"},
		{Character: "🐘", Description: "Elephant"},
		{Character: "🐰", Description: "Rabbit"},
		{Character: "🐼", Description: "Panda"},
		{Character: "🐓", Description: "Rooster"},
		{Character: "🐧", Description: "Penguin"},
		{Character: "🐢", Description: "Turtle"},
		{Character: "🐟", Description: "Fish"},
		{Character: "🐙", Description: "Octopus"},
		{Character: "🦋", Description: "Butterfly"},
		{Character: "🌷", Description: "Flower"},
		{Character: "🌳", Description: "Tree"},
		{Character: "🌵", Description: "Cactus"},
		{Character: "🍄", Description: "Mushroom"},
		{Character: "🌏", Description: "Globe"},
		{Character: "🌙", Description: "Moon"},
		{Character: "☁️", Description: "Cloud"},
		{Character: "🔥", Description: "Fire"},
		{Character: "🍌", Description: "Banana"},
		{Character: "🍎", Description: "Apple"},
		{Character: "🍓", Description: "Strawberry"},
		{Character: "🌽", Description: "Corn"},
		{Character: "🍕", Description: "Pizza"},
		{Character: "🎂", Description: "Cake"},
		{Character: "❤️", Description: "Heart"},
		{Character: "😀", Description: "Smiley"},
		{Character: "🤖", Description: "Robot"},
		{Character: "🎩", Description: "Hat"},
		{Character: "👓", Description: "Glasses"},
		{Character: "🔧", Description: "Spanner"},
		{Character: "🎅", Description: "Santa"},
		{Character: "👍", Description: "Thumbs Up"},
		{Character: "☂️", Description: "Umbrella"},
		{Character: "⌛", Description: "Hourglass"},
		{Character: "⏰", Description: "Clock"},
		{Character: "🎁", Description: "Gift"},
		{Character: "💡", Description: "Light Bulb"},
		{Character: "📕", Description: "Book"},
		{Character: "✏️", Description: "Pencil"},
		{Character: "📎", Description: "Paperclip"},
		{Character: "✂️", Description: "Scissors"},
		{Character: "🔒", Description: "Lock"},
		{Character: "🔑", Description: "Key"},
		{Character: "🔨", Description: "Hammer"},
		{Character: "☎️", Description: "Telephone"},
		{Character: "🏁", Description: "Flag"},
		{Character: "🚂", Description: "Train"},
		{Character: "🚲", Description: "Bicycle"},
		{Character: "✈️", Description: "Aeroplane"},
		{Character: "🚀", Description: "Rocket"},
		{Character: "🏆", Description: "Trophy"},
		{Character: "⚽", Description: "Ball"},
		{Character: "🎸", Description: "Guitar"},
		{Character: "🎺", Description: "Trumpet"},
		{Character: "🔔", Description: "Bell"},
		{Character: "⚓", Description: "Anchor"},
		{Character: "🎧", Description: "Headphones"},
		{Character: "📁", Description: "Folder"},
		{Character: "📌", Description: "Pin"},
		{Character: "0️⃣", Description: "Zero"},
		{Character: "1️⃣", Description: "One"},
		{Character: "2️⃣", Description: "Two"},
		{Character: "3️⃣", Description: "Three"},
		{Character: "4️⃣", Description: "Four"},
		{Character: "5️⃣", Description: "Five"},
		{Character: "6️⃣", Description: "Six"},
		{Character: "7️⃣", Description: "Seven"},
		{Character: "8️⃣", Description: "Eight"},
		{Character: "9️⃣", Description: "Nine"},
		{Character: "♻️", Description: "Recycle"},
		{Character: "⚡", Description: "Lightning"},
		{Character: "💎", Description: "Diamond"},
		{Character: "🌈", Description: "Rainbow"},
		{Character: "❄️", Description: "Snowflake"},
		{Character: "🌊", Description: "Wave"},
		{Character: "🎲", Description: "Dice"},
		{Character: "🧲", Description: "Magnet"},
		{Character: "🪐", Description: "Saturn"},
		{Character: "🌋", Description: "Volcano"},
		{Character: "⭐", Description: "Star"},
		{Character: "🐬", Description: "Dolphin"},
		{Character: "🦊", Description: "Fox"},
		{Character: "🦉", Description: "Owl"},
		{Character: "🏔️", Description: "Mountain"},
		{Character: "🧊", Description: "Ice"},
		{Character: "🎯", Description: "Target"},
		{Character: "🛡️", Description: "Shield"},
		{Character: "⚙️", Description: "Gear"},
		{Character: "🔱", Description: "Trident"},
		{Character: "🦀", Description: "Crab"},
		{Character: "🦈", Description: "Shark"},
		{Character: "🐸", Description: "Frog"},
		{Character: "🦩", Description: "Flamingo"},
		{Character: "🦜", Description: "Parrot"},
		{Character: "🐍", Description: "Snake"},
		{Character: "🦞", Description: "Lobster"},
		{Character: "🐪", Description: "Camel"},
		{Character: "🦒", Description: "Giraffe"},
		{Character: "🐊", Description: "Crocodile"},
		{Character: "🍉", Description: "Watermelon"},
		{Character: "🍇", Description: "Grapes"},
		{Character: "🍒", Description: "Cherry"},
		{Character: "🥥", Description: "Coconut"},
		{Character: "🌶️", Description: "Chilli"},
		{Character: "🧀", Description: "Cheese"},
		{Character: "🍩", Description: "Donut"},
		{Character: "🧁", Description: "Cupcake"},
		{Character: "🍿", Description: "Popcorn"},
		{Character: "🏠", Description: "House"},
		{Character: "🏰", Description: "Castle"},
		{Character: "⛵", Description: "Sailboat"},
		{Character: "🚁", Description: "Helicopter"},
		{Character: "🛸", Description: "UFO"},
		{Character: "🎭", Description: "Theatre"},
		{Character: "🎪", Description: "Circus"},
		{Character: "🎈", Description: "Balloon"},
		{Character: "🧩", Description: "Puzzle"},
		{Character: "🪁", Description: "Kite"},
		{Character: "🏹", Description: "Bow"},
		{Character: "🪴", Description: "Plant"},
		{Character: "🌻", Description: "Sunflower"},
		{Character: "🌴", Description: "Palm"},
		{Character: "🍂", Description: "Leaf"},
		{Character: "🐚", Description: "Shell"},
		{Character: "🦎", Description: "Lizard"},
		{Character: "🦭", Description: "Seal"},
		{Character: "🦔", Description: "Hedgehog"},
		{Character: "🦚", Description: "Peacock"},
		{Character: "🐞", Description: "Ladybug"},
		{Character: "🕷️", Description: "Spider"},
		{Character: "🎱", Description: "Billiards"},
		{Character: "🛶", Description: "Canoe"},
		{Character: "🎻", Description: "Violin"},
		{Character: "🥁", Description: "Drum"},
		{Character: "🎤", Description: "Microphone"},
		{Character: "🔭", Description: "Telescope"},
		{Character: "🔬", Description: "Microscope"},
		{Character: "💊", Description: "Pill"},
		{Character: "🧬", Description: "DNA"},
		{Character: "🧪", Description: "Test Tube"},
		{Character: "🕯️", Description: "Candle"},
		{Character: "💰", Description: "Money Bag"},
		{Character: "👑", Description: "Crown"},
		{Character: "🪶", Description: "Feather"},
		{Character: "⛏️", Description: "Pickaxe"},
		{Character: "🪨", Description: "Rock"},
		{Character: "🏮", Description: "Lantern"},
		{Character: "🎀", Description: "Ribbon"},
		{Character: "🪵", Description: "Log"},
		{Character: "🛞", Description: "Wheel"},
		{Character: "🪜", Description: "Ladder"},
		{Character: "🧯", Description: "Extinguisher"},
		{Character: "🎓", Description: "Graduation"},
		{Character: "💍", Description: "Ring"},
		{Character: "🩺", Description: "Stethoscope"},
		{Character: "🪃", Description: "Boomerang"},
		{Character: "🏺", Description: "Amphora"},
		{Character: "🗿", Description: "Moai"},
		{Character: "🗽", Description: "Liberty"},
		{Character: "⛩️", Description: "Shrine"},
		{Character: "🕌", Description: "Mosque"},
		{Character: "🎡", Description: "Ferris Wheel"},
		{Character: "🎢", Description: "Roller Coaster"},
		{Character: "🚢", Description: "Ship"},
		{Character: "🛰️", Description: "Satellite"},
		{Character: "🌠", Description: "Shooting Star"},
		{Character: "🌀", Description: "Cyclone"},
		{Character: "🔮", Description: "Crystal Ball"},
		{Character: "🪩", Description: "Mirror Ball"},
		{Character: "🎵", Description: "Music"},
		{Character: "🕹️", Description: "Joystick"},
		{Character: "🖨️", Description: "Printer"},
		{Character: "💾", Description: "Floppy"},
		{Character: "🔋", Description: "Battery"},
		{Character: "📡", Description: "Dish"},
		{Character: "🏋️", Description: "Weightlifter"},
		{Character: "🤿", Description: "Diving"},
		{Character: "🛹", Description: "Skateboard"},
		{Character: "🧳", Description: "Suitcase"},
		{Character: "🪝", Description: "Hook"},
		{Character: "🧸", Description: "Teddy Bear"},
		{Character: "🎏", Description: "Carp Streamer"},
		{Character: "🏕️", Description: "Camping"},
		{Character: "🗺️", Description: "World Map"},
		{Character: "🧶", Description: "Yarn"},
		{Character: "🎐", Description: "Wind Chime"},
		{Character: "🦇", Description: "Bat"},
		{Character: "🛒", Description: "Cart"},
		{Character: "🦷", Description: "Tooth"},
		{Character: "🫀", Description: "Heart Organ"},
		{Character: "🧠", Description: "Brain"},
		{Character: "👁️", Description: "Eye"},
		{Character: "🦴", Description: "Bone"},
		{Character: "🪸", Description: "Coral"},
		{Character: "🐌", Description: "Snail"},
		{Character: "🦂", Description: "Scorpion"},
		{Character: "🕊️", Description: "Dove"},
		{Character: "🦙", Description: "Llama"},
		{Character: "🦘", Description: "Kangaroo"},
		{Character: "🦫", Description: "Beaver"},
		{Character: "🦦", Description: "Otter"},
		{Character: "🦥", Description: "Sloth"},
		{Character: "🍑", Description: "Peach"},
		{Character: "🥝", Description: "Kiwi"},
		{Character: "🥑", Description: "Avocado"},
		{Character: "🥕", Description: "Carrot"},
		{Character: "🥨", Description: "Pretzel"},
		{Character: "🥐", Description: "Croissant"},
		{Character: "🍭", Description: "Lollipop"},
		{Character: "🫐", Description: "Blueberry"},
		{Character: "🥦", Description: "Broccoli"},
		{Character: "🌰", Description: "Chestnut"},
		{Character: "🥜", Description: "Peanut"},
		{Character: "🍯", Description: "Honey"},
		{Character: "🧂", Description: "Salt"},
		{Character: "🫖", Description: "Teapot"},
		{Character: "🍵", Description: "Tea"},
		{Character: "🧃", Description: "Juice Box"},
		{Character: "🪘", Description: "Long Drum"},
		{Character: "🎷", Description: "Saxophone"},
		{Character: "🎹", Description: "Piano"},
		{Character: "🪗", Description: "Accordion"},
		{Character: "🏗️", Description: "Crane"},
		{Character: "🗼", Description: "Tower"},
		{Character: "⛲", Description: "Fountain"},
		{Character: "🎠", Description: "Carousel"},
		{Character: "🛥️", Description: "Speedboat"},
		{Character: "🚜", Description: "Tractor"},
		{Character: "🚒", Description: "Fire Engine"},
		{Character: "🚑", Description: "Ambulance"},
		{Character: "🛴", Description: "Scooter"},
		{Character: "🪂", Description: "Parachute"},
		{Character: "🏄", Description: "Surfer"},
		{Character: "⛷️", Description: "Skier"},
		{Character: "🏊", Description: "Swimmer"},
		{Character: "🛷", Description: "Sled"},
		{Character: "🧨", Description: "Firecracker"},
		{Character: "🎃", Description: "Pumpkin"},
		{Character: "🎳", Description: "Bowling"},
		{Character: "🏓", Description: "Ping Pong"},
		{Character: "🥊", Description: "Boxing"},
		{Character: "🏒", Description: "Hockey"},
		{Character: "🎿", Description: "Ski"},
		{Character: "🪀", Description: "Yo-Yo"},
		{Character: "🛼", Description: "Roller Skate"},
		{Character: "🧗", Description: "Climber"},
		{Character: "🏇", Description: "Jockey"},
		{Character: "🪈", Description: "Flute"},
		{Character: "📯", Description: "Horn"},
		{Character: "🎙️", Description: "Studio Mic"},
		{Character: "📻", Description: "Radio"},
		{Character: "📺", Description: "Television"},
		{Character: "🖥️", Description: "Desktop"},
		{Character: "💿", Description: "CD"},
		{Character: "🔦", Description: "Flashlight"},
		{Character: "🪫", Description: "Low Battery"},
		{Character: "🧰", Description: "Toolbox"},
		{Character: "🪚", Description: "Saw"},
		{Character: "🔩", Description: "Nut & Bolt"},
		{Character: "🧱", Description: "Brick"},
		{Character: "⛓️", Description: "Chain"},
		{Character: "🪣", Description: "Bucket"},
		{Character: "🪦", Description: "Headstone"},
		{Character: "🔗", Description: "Link"},
		{Character: "🪟", Description: "Window"},
		{Character: "🚪", Description: "Door"},
		{Character: "🛏️", Description: "Bed"},
		{Character: "🪑", Description: "Chair"},
		{Character: "🚿", Description: "Shower"},
		{Character: "🧴", Description: "Lotion"},
		{Character: "🧽", Description: "Sponge"},
		{Character: "🕶️", Description: "Sunglasses"},
		{Character: "🥾", Description: "Boot"},
		{Character: "👒", Description: "Sun Hat"},
		{Character: "🧤", Description: "Gloves"},
		{Character: "🧣", Description: "Scarf"},
		{Character: "👔", Description: "Necktie"},
		{Character: "👗", Description: "Dress"},
		{Character: "🩰", Description: "Ballet"},
		{Character: "🪭", Description: "Fan"},
		{Character: "💄", Description: "Lipstick"},
		{Character: "💈", Description: "Barber Pole"},
		{Character: "🔍", Description: "Magnifier"},
		{Character: "📿", Description: "Prayer Beads"},
		{Character: "🪬", Description: "Hamsa"},
		{Character: "♟️", Description: "Chess Pawn"},
		{Character: "🀄", Description: "Mahjong"},
		{Character: "🃏", Description: "Joker"},
		{Character: "🖼️", Description: "Frame"},
		{Character: "🪆", Description: "Nesting Doll"},
		{Character: "🏷️", Description: "Label"},
		{Character: "📮", Description: "Postbox"},
		{Character: "🗑️", Description: "Wastebasket"},
		{Character: "🚩", Description: "Red Flag"},
		{Character: "🏴‍☠️", Description: "Pirate Flag"},
		{Character: "🪧", Description: "Placard"},
		{Character: "📬", Description: "Mailbox"},
		{Character: "🪙", Description: "Coin"},
		{Character: "💳", Description: "Credit Card"},
		{Character: "📐", Description: "Triangle Ruler"},
		{Character: "🗓️", Description: "Calendar"},
		{Character: "📊", Description: "Bar Chart"},
		{Character: "🔖", Description: "Bookmark"},
		{Character: "🏵️", Description: "Rosette"},
		{Character: "🎗️", Description: "Reminder Ribbon"},
		{Character: "🪢", Description: "Knot"},
		{Character: "🩻", Description: "X-Ray"},
		{Character: "🪪", Description: "ID Card"},
		{Character: "🛗", Description: "Elevator"},
		{Character: "🚦", Description: "Traffic Light"},
		{Character: "⛽", Description: "Fuel Pump"},
		{Character: "🚧", Description: "Construction"},
		{Character: "🛟", Description: "Ring Buoy"},
		{Character: "🪔", Description: "Diya Lamp"},
		{Character: "🎑", Description: "Moon Viewing"},
		{Character: "🧧", Description: "Red Envelope"},
		{Character: "🎍", Description: "Bamboo"},
		{Character: "🪷", Description: "Lotus"},
		{Character: "🍁", Description: "Maple Leaf"},
		{Character: "☘️", Description: "Shamrock"},
		{Character: "🦠", Description: "Microbe"},
		{Character: "🪺", Description: "Nest"},
		{Character: "🧮", Description: "Abacus"},
		{Character: "📣", Description: "Megaphone"},
		{Character: "🏅", Description: "Medal"},
		{Character: "⛺", Description: "Tent"},
		{Character: "🫧", Description: "Soap Bubble"},
		{Character: "🏳️‍🌈", Description: "Pride Flag"},
		{Character: "🏳️‍⚧️", Description: "Transgender Flag"},
		{Character: "🏴", Description: "Black Flag"},
		{Character: "🇯🇵", Description: "Japan"},
		{Character: "🇧🇷", Description: "Brazil"},
		{Character: "🇨🇦", Description: "Canada"},
		{Character: "☀️", Description: "Sun"},
		{Character: "🌕", Description: "Full Moon"},
		{Character: "🔰", Description: "Beginner"},
		{Character: "♾️", Description: "Infinity"},
		{Character: "🏝️", Description: "Island"},
		{Character: "🌾", Description: "Rice"},
		{Character: "🫶", Description: "Heart Hands"},
		{Character: "🦤", Description: "Dodo"},
		{Character: "🫏", Description: "Donkey"},
		{Character: "🐉", Description: "Dragon"},
		{Character: "🦬", Description: "Bison"},
		{Character: "🪻", Description: "Hyacinth"},
	}
}
