FROM golang:1.21

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o smtpLogger ./tools/smtp/smtpLogger.go

# This container exposes port 8025 to the outside world
EXPOSE 8025

# Run the binary program produced by `go build`
CMD ["./smtpLogger"]
