package cacheheader

/******************************************
 * HTTP Headers
 ******************************************/

// HeaderAge is the "Age" response header: seconds since the response was generated by the origin
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age
const HeaderAge = "age"

// HeaderCacheControl is the "Cache-Control" header that carries every directive below
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
const HeaderCacheControl = "Cache-Control"

/******************************************
 * Cache-Control Directives
 ******************************************/

// DirectiveMaxAge is "max-age": how long a response stays fresh, in seconds
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#max-age
const DirectiveMaxAge = "max-age"

// DirectiveSMaxAge is "s-maxage": max-age for shared caches, which overrides max-age for them
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#s-max-age
const DirectiveSMaxAge = "s-maxage"

// DirectiveNoCache is "no-cache": a cache may store the response but must revalidate before reusing it
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-cache
const DirectiveNoCache = "no-cache"

// DirectiveNoStore is "no-store": the response must not be written to any cache
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-store
const DirectiveNoStore = "no-store"

// DirectiveNoTransform is "no-transform": an intermediary must not alter the payload
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-transform
const DirectiveNoTransform = "no-transform"

// DirectiveMustRevalidate is "must-revalidate": once stale, the response must be revalidated, never served
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#must-revalidate
const DirectiveMustRevalidate = "must-revalidate"

// DirectiveProxyRevalidate is "proxy-revalidate": must-revalidate, for shared caches only
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#proxy-revalidate
const DirectiveProxyRevalidate = "proxy-revalidate"

// DirectiveMustUnderstand is "must-understand": store the response only if the status code is understood
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#must-understand
const DirectiveMustUnderstand = "must-understand"

// DirectivePrivate is "private": only a browser cache may store the response, not a shared one
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#private
const DirectivePrivate = "private"

// DirectivePublic is "public": any cache may store the response, even when it is normally not cacheable
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#public
const DirectivePublic = "public"

// DirectiveImmutable is "immutable": the body will not change, so do not revalidate while fresh
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#immutable
const DirectiveImmutable = "immutable"

// DirectiveStaleWhileRevalidate is "stale-while-revalidate": serve a stale response while refreshing it in the background
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-while-revalidate
const DirectiveStaleWhileRevalidate = "stale-while-revalidate"

// DirectiveStaleIfError is "stale-if-error": serve a stale response when revalidation fails
//
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-if-error
const DirectiveStaleIfError = "stale-if-error"
