package camper

const IntentTypeAccept = "https://w3id.org/fep/3b86/Accept"
const IntentTypeAdd = "https://w3id.org/fep/3b86/Add"
const IntentTypeAnnounce = "https://w3id.org/fep/3b86/Announce"
const IntentTypeArrive = "https://w3id.org/fep/3b86/Arrive"
const IntentTypeBlock = "https://w3id.org/fep/3b86/Block"
const IntentTypeCreate = "https://w3id.org/fep/3b86/Create"
const IntentTypeDelete = "https://w3id.org/fep/3b86/Delete"
const IntentTypeDislike = "https://w3id.org/fep/3b86/Dislike"
const IntentTypeFlag = "https://w3id.org/fep/3b86/Flag"
const IntentTypeFollow = "https://w3id.org/fep/3b86/Follow"
const IntentTypeIgnore = "https://w3id.org/fep/3b86/Ignore"
const IntentTypeInvite = "https://w3id.org/fep/3b86/Invite"
const IntentTypeJoin = "https://w3id.org/fep/3b86/Join"
const IntentTypeLeave = "https://w3id.org/fep/3b86/Leave"
const IntentTypeLike = "https://w3id.org/fep/3b86/Like"
const IntentTypeListen = "https://w3id.org/fep/3b86/Listen"
const IntentTypeMove = "https://w3id.org/fep/3b86/Move"
const IntentTypeOffer = "https://w3id.org/fep/3b86/Offer"
const IntentTypeQuestion = "https://w3id.org/fep/3b86/Question"
const IntentTypeRead = "https://w3id.org/fep/3b86/Read"
const IntentTypeReject = "https://w3id.org/fep/3b86/Reject"
const IntentTypeRemove = "https://w3id.org/fep/3b86/Remove"
const IntentTypeTentativeAccept = "https://w3id.org/fep/3b86/TentativeAccept"
const IntentTypeTentativeReject = "https://w3id.org/fep/3b86/TentativeReject"
const IntentTypeTravel = "https://w3id.org/fep/3b86/Travel"
const IntentTypeUndo = "https://w3id.org/fep/3b86/Undo"
const IntentTypeUpdate = "https://w3id.org/fep/3b86/Update"
const IntentTypeView = "https://w3id.org/fep/3b86/View"

// Special case for opening an Object without sending a "View" activity
const IntentTypeObject = "https://w3id.org/fep/3b86/Object"
